services:
  - type: web
    name: n8n-automation
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node start-n8n.js
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: N8N_USER_FOLDER
        value: /data
      - key: N8N_DATA_FOLDER
        value: /data
      - key: N8N_ENCRYPTION_KEY
        value: 0f5de54f82541d5970f922290cd0fe0e4d7c7c70471d0170
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-automation
          property: host
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: n8n-automation
          property: host
      - key: N8N_DATABASE_TYPE
        value: sqlite
      - key: N8N_DATABASE_SQLITE_DATABASE
        value: /data/database/n8n.db
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_LOG_OUTPUT
        value: console,file
      - key: N8N_LOG_FILE_LOCATION
        value: /data/logs/
      - key: N8N_DISABLE_UI
        value: "false"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"
      - key: N8N_GIT_NODE_DISABLE_BARE_REPOS
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_CUSTOM_EXTENSIONS
        value: /data/custom
      - key: N8N_TEMPLATES_ENABLED
        value: "true"
      - key: N8N_TEMPLATES_HOST
        value: https://api.n8n.io
      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: "true"
      - key: N8N_VERSION_NOTIFICATIONS_ENDPOINT
        value: https://api.n8n.io/versions/
      - key: N8N_PERSONALIZATION_ENABLED
        value: "true"
      - key: DB_SQLITE_POOL_SIZE
        value: "10"
