services:
  - type: web
    name: n8n-automation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start-n8n-simple.js
    envVars:
      - key: N8N_USER_FOLDER
        value: /opt/render/project/src
      - key: N8N_DATA_FOLDER
        value: /opt/render/project/src
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-automation
          property: host
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: n8n-automation
          property: host
      - key: N8N_DATABASE_TYPE
        value: sqlite
      - key: N8N_DATABASE_SQLITE_DATABASE
        value: /opt/render/project/src/database/n8n.db
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_LOG_OUTPUT
        value: console
      - key: N8N_DISABLE_UI
        value: "false"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"
